spring:
  data:
    mongodb:
      uri: mongodb://localhost:21017/ats-applicant
  application:
    name: ATS-applicant

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1120/eureka