spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
  application:
    name: ATS-process

camunda.bpm.admin-user:
  id: ivan
  password: ivan

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1120/eureka